/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.Data25ForecastGet200ResponseCityCoord;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25ForecastGet200ResponseCity
 */
@JsonPropertyOrder({
  Data25ForecastGet200ResponseCity.JSON_PROPERTY_ID,
  Data25ForecastGet200ResponseCity.JSON_PROPERTY_NAME,
  Data25ForecastGet200ResponseCity.JSON_PROPERTY_COUNTRY,
  Data25ForecastGet200ResponseCity.JSON_PROPERTY_COORD
})
@JsonTypeName("_data_2_5_forecast_get_200_response_city")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25ForecastGet200ResponseCity {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Integer id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_COORD = "coord";
  @javax.annotation.Nullable
  private Data25ForecastGet200ResponseCityCoord coord;

  public Data25ForecastGet200ResponseCity() {
  }

  public Data25ForecastGet200ResponseCity id(@javax.annotation.Nullable Integer id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Integer id) {
    this.id = id;
  }

  public Data25ForecastGet200ResponseCity name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public Data25ForecastGet200ResponseCity country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public Data25ForecastGet200ResponseCity coord(@javax.annotation.Nullable Data25ForecastGet200ResponseCityCoord coord) {
    
    this.coord = coord;
    return this;
  }

  /**
   * Get coord
   * @return coord
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Data25ForecastGet200ResponseCityCoord getCoord() {
    return coord;
  }


  @JsonProperty(value = JSON_PROPERTY_COORD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCoord(@javax.annotation.Nullable Data25ForecastGet200ResponseCityCoord coord) {
    this.coord = coord;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25ForecastGet200ResponseCity data25ForecastGet200ResponseCity = (Data25ForecastGet200ResponseCity) o;
    return Objects.equals(this.id, data25ForecastGet200ResponseCity.id) &&
        Objects.equals(this.name, data25ForecastGet200ResponseCity.name) &&
        Objects.equals(this.country, data25ForecastGet200ResponseCity.country) &&
        Objects.equals(this.coord, data25ForecastGet200ResponseCity.coord);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, country, coord);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25ForecastGet200ResponseCity {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    coord: ").append(toIndentedString(coord)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

