/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25ForecastGet200ResponseCityCoord
 */
@JsonPropertyOrder({
  Data25ForecastGet200ResponseCityCoord.JSON_PROPERTY_LAT,
  Data25ForecastGet200ResponseCityCoord.JSON_PROPERTY_LON
})
@JsonTypeName("_data_2_5_forecast_get_200_response_city_coord")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25ForecastGet200ResponseCityCoord {
  public static final String JSON_PROPERTY_LAT = "lat";
  @javax.annotation.Nullable
  private BigDecimal lat;

  public static final String JSON_PROPERTY_LON = "lon";
  @javax.annotation.Nullable
  private BigDecimal lon;

  public Data25ForecastGet200ResponseCityCoord() {
  }

  public Data25ForecastGet200ResponseCityCoord lat(@javax.annotation.Nullable BigDecimal lat) {
    
    this.lat = lat;
    return this;
  }

  /**
   * Get lat
   * @return lat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLat() {
    return lat;
  }


  @JsonProperty(value = JSON_PROPERTY_LAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLat(@javax.annotation.Nullable BigDecimal lat) {
    this.lat = lat;
  }

  public Data25ForecastGet200ResponseCityCoord lon(@javax.annotation.Nullable BigDecimal lon) {
    
    this.lon = lon;
    return this;
  }

  /**
   * Get lon
   * @return lon
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLon() {
    return lon;
  }


  @JsonProperty(value = JSON_PROPERTY_LON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLon(@javax.annotation.Nullable BigDecimal lon) {
    this.lon = lon;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25ForecastGet200ResponseCityCoord data25ForecastGet200ResponseCityCoord = (Data25ForecastGet200ResponseCityCoord) o;
    return Objects.equals(this.lat, data25ForecastGet200ResponseCityCoord.lat) &&
        Objects.equals(this.lon, data25ForecastGet200ResponseCityCoord.lon);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lat, lon);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25ForecastGet200ResponseCityCoord {\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

