/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Data25AirPollutionGet200ResponseListInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25AirPollutionGet200Response
 */
@JsonPropertyOrder({
  Data25AirPollutionGet200Response.JSON_PROPERTY_LIST
})
@JsonTypeName("_data_2_5_air_pollution_get_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25AirPollutionGet200Response {
  public static final String JSON_PROPERTY_LIST = "list";
  @javax.annotation.Nullable
  private List<Data25AirPollutionGet200ResponseListInner> _list = new ArrayList<>();

  public Data25AirPollutionGet200Response() {
  }

  public Data25AirPollutionGet200Response _list(@javax.annotation.Nullable List<Data25AirPollutionGet200ResponseListInner> _list) {
    
    this._list = _list;
    return this;
  }

  public Data25AirPollutionGet200Response addListItem(Data25AirPollutionGet200ResponseListInner _listItem) {
    if (this._list == null) {
      this._list = new ArrayList<>();
    }
    this._list.add(_listItem);
    return this;
  }

  /**
   * Get _list
   * @return _list
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Data25AirPollutionGet200ResponseListInner> getList() {
    return _list;
  }


  @JsonProperty(value = JSON_PROPERTY_LIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setList(@javax.annotation.Nullable List<Data25AirPollutionGet200ResponseListInner> _list) {
    this._list = _list;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25AirPollutionGet200Response data25AirPollutionGet200Response = (Data25AirPollutionGet200Response) o;
    return Objects.equals(this._list, data25AirPollutionGet200Response._list);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_list);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25AirPollutionGet200Response {\n");
    sb.append("    _list: ").append(toIndentedString(_list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

