/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Data25ForecastGet200ResponseCity;
import org.openapitools.client.model.Data25ForecastGet200ResponseListInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25ForecastGet200Response
 */
@JsonPropertyOrder({
  Data25ForecastGet200Response.JSON_PROPERTY_COD,
  Data25ForecastGet200Response.JSON_PROPERTY_MESSAGE,
  Data25ForecastGet200Response.JSON_PROPERTY_CNT,
  Data25ForecastGet200Response.JSON_PROPERTY_LIST,
  Data25ForecastGet200Response.JSON_PROPERTY_CITY
})
@JsonTypeName("_data_2_5_forecast_get_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25ForecastGet200Response {
  public static final String JSON_PROPERTY_COD = "cod";
  @javax.annotation.Nullable
  private String cod;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nullable
  private BigDecimal message;

  public static final String JSON_PROPERTY_CNT = "cnt";
  @javax.annotation.Nullable
  private Integer cnt;

  public static final String JSON_PROPERTY_LIST = "list";
  @javax.annotation.Nullable
  private List<Data25ForecastGet200ResponseListInner> _list = new ArrayList<>();

  public static final String JSON_PROPERTY_CITY = "city";
  @javax.annotation.Nullable
  private Data25ForecastGet200ResponseCity city;

  public Data25ForecastGet200Response() {
  }

  public Data25ForecastGet200Response cod(@javax.annotation.Nullable String cod) {
    
    this.cod = cod;
    return this;
  }

  /**
   * Get cod
   * @return cod
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCod() {
    return cod;
  }


  @JsonProperty(value = JSON_PROPERTY_COD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCod(@javax.annotation.Nullable String cod) {
    this.cod = cod;
  }

  public Data25ForecastGet200Response message(@javax.annotation.Nullable BigDecimal message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getMessage() {
    return message;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@javax.annotation.Nullable BigDecimal message) {
    this.message = message;
  }

  public Data25ForecastGet200Response cnt(@javax.annotation.Nullable Integer cnt) {
    
    this.cnt = cnt;
    return this;
  }

  /**
   * Get cnt
   * @return cnt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCnt() {
    return cnt;
  }


  @JsonProperty(value = JSON_PROPERTY_CNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCnt(@javax.annotation.Nullable Integer cnt) {
    this.cnt = cnt;
  }

  public Data25ForecastGet200Response _list(@javax.annotation.Nullable List<Data25ForecastGet200ResponseListInner> _list) {
    
    this._list = _list;
    return this;
  }

  public Data25ForecastGet200Response addListItem(Data25ForecastGet200ResponseListInner _listItem) {
    if (this._list == null) {
      this._list = new ArrayList<>();
    }
    this._list.add(_listItem);
    return this;
  }

  /**
   * Get _list
   * @return _list
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Data25ForecastGet200ResponseListInner> getList() {
    return _list;
  }


  @JsonProperty(value = JSON_PROPERTY_LIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setList(@javax.annotation.Nullable List<Data25ForecastGet200ResponseListInner> _list) {
    this._list = _list;
  }

  public Data25ForecastGet200Response city(@javax.annotation.Nullable Data25ForecastGet200ResponseCity city) {
    
    this.city = city;
    return this;
  }

  /**
   * Get city
   * @return city
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Data25ForecastGet200ResponseCity getCity() {
    return city;
  }


  @JsonProperty(value = JSON_PROPERTY_CITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@javax.annotation.Nullable Data25ForecastGet200ResponseCity city) {
    this.city = city;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25ForecastGet200Response data25ForecastGet200Response = (Data25ForecastGet200Response) o;
    return Objects.equals(this.cod, data25ForecastGet200Response.cod) &&
        Objects.equals(this.message, data25ForecastGet200Response.message) &&
        Objects.equals(this.cnt, data25ForecastGet200Response.cnt) &&
        Objects.equals(this._list, data25ForecastGet200Response._list) &&
        Objects.equals(this.city, data25ForecastGet200Response.city);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cod, message, cnt, _list, city);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25ForecastGet200Response {\n");
    sb.append("    cod: ").append(toIndentedString(cod)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    cnt: ").append(toIndentedString(cnt)).append("\n");
    sb.append("    _list: ").append(toIndentedString(_list)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

