/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Data25WeatherGet200ResponseMain;
import org.openapitools.client.model.Data25WeatherGet200ResponseWeatherInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25WeatherGet200Response
 */
@JsonPropertyOrder({
  Data25WeatherGet200Response.JSON_PROPERTY_WEATHER,
  Data25WeatherGet200Response.JSON_PROPERTY_MAIN
})
@JsonTypeName("_data_2_5_weather_get_200_response")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25WeatherGet200Response {
  public static final String JSON_PROPERTY_WEATHER = "weather";
  @javax.annotation.Nullable
  private List<Data25WeatherGet200ResponseWeatherInner> weather = new ArrayList<>();

  public static final String JSON_PROPERTY_MAIN = "main";
  @javax.annotation.Nullable
  private Data25WeatherGet200ResponseMain main;

  public Data25WeatherGet200Response() {
  }

  public Data25WeatherGet200Response weather(@javax.annotation.Nullable List<Data25WeatherGet200ResponseWeatherInner> weather) {
    
    this.weather = weather;
    return this;
  }

  public Data25WeatherGet200Response addWeatherItem(Data25WeatherGet200ResponseWeatherInner weatherItem) {
    if (this.weather == null) {
      this.weather = new ArrayList<>();
    }
    this.weather.add(weatherItem);
    return this;
  }

  /**
   * Get weather
   * @return weather
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEATHER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Data25WeatherGet200ResponseWeatherInner> getWeather() {
    return weather;
  }


  @JsonProperty(value = JSON_PROPERTY_WEATHER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeather(@javax.annotation.Nullable List<Data25WeatherGet200ResponseWeatherInner> weather) {
    this.weather = weather;
  }

  public Data25WeatherGet200Response main(@javax.annotation.Nullable Data25WeatherGet200ResponseMain main) {
    
    this.main = main;
    return this;
  }

  /**
   * Get main
   * @return main
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Data25WeatherGet200ResponseMain getMain() {
    return main;
  }


  @JsonProperty(value = JSON_PROPERTY_MAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMain(@javax.annotation.Nullable Data25WeatherGet200ResponseMain main) {
    this.main = main;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25WeatherGet200Response data25WeatherGet200Response = (Data25WeatherGet200Response) o;
    return Objects.equals(this.weather, data25WeatherGet200Response.weather) &&
        Objects.equals(this.main, data25WeatherGet200Response.main);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weather, main);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25WeatherGet200Response {\n");
    sb.append("    weather: ").append(toIndentedString(weather)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

