/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25AirPollutionGet200ResponseListInnerComponents
 */
@JsonPropertyOrder({
  Data25AirPollutionGet200ResponseListInnerComponents.JSON_PROPERTY_PM25,
  Data25AirPollutionGet200ResponseListInnerComponents.JSON_PROPERTY_PM10,
  Data25AirPollutionGet200ResponseListInnerComponents.JSON_PROPERTY_CO
})
@JsonTypeName("_data_2_5_air_pollution_get_200_response_list_inner_components")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25AirPollutionGet200ResponseListInnerComponents {
  public static final String JSON_PROPERTY_PM25 = "pm2_5";
  @javax.annotation.Nullable
  private BigDecimal pm25;

  public static final String JSON_PROPERTY_PM10 = "pm10";
  @javax.annotation.Nullable
  private BigDecimal pm10;

  public static final String JSON_PROPERTY_CO = "co";
  @javax.annotation.Nullable
  private BigDecimal co;

  public Data25AirPollutionGet200ResponseListInnerComponents() {
  }

  public Data25AirPollutionGet200ResponseListInnerComponents pm25(@javax.annotation.Nullable BigDecimal pm25) {
    
    this.pm25 = pm25;
    return this;
  }

  /**
   * Get pm25
   * @return pm25
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PM25, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPm25() {
    return pm25;
  }


  @JsonProperty(value = JSON_PROPERTY_PM25, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPm25(@javax.annotation.Nullable BigDecimal pm25) {
    this.pm25 = pm25;
  }

  public Data25AirPollutionGet200ResponseListInnerComponents pm10(@javax.annotation.Nullable BigDecimal pm10) {
    
    this.pm10 = pm10;
    return this;
  }

  /**
   * Get pm10
   * @return pm10
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PM10, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPm10() {
    return pm10;
  }


  @JsonProperty(value = JSON_PROPERTY_PM10, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPm10(@javax.annotation.Nullable BigDecimal pm10) {
    this.pm10 = pm10;
  }

  public Data25AirPollutionGet200ResponseListInnerComponents co(@javax.annotation.Nullable BigDecimal co) {
    
    this.co = co;
    return this;
  }

  /**
   * Get co
   * @return co
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getCo() {
    return co;
  }


  @JsonProperty(value = JSON_PROPERTY_CO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCo(@javax.annotation.Nullable BigDecimal co) {
    this.co = co;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25AirPollutionGet200ResponseListInnerComponents data25AirPollutionGet200ResponseListInnerComponents = (Data25AirPollutionGet200ResponseListInnerComponents) o;
    return Objects.equals(this.pm25, data25AirPollutionGet200ResponseListInnerComponents.pm25) &&
        Objects.equals(this.pm10, data25AirPollutionGet200ResponseListInnerComponents.pm10) &&
        Objects.equals(this.co, data25AirPollutionGet200ResponseListInnerComponents.co);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pm25, pm10, co);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25AirPollutionGet200ResponseListInnerComponents {\n");
    sb.append("    pm25: ").append(toIndentedString(pm25)).append("\n");
    sb.append("    pm10: ").append(toIndentedString(pm10)).append("\n");
    sb.append("    co: ").append(toIndentedString(co)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

