/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.Data25AirPollutionGet200ResponseListInnerComponents;
import org.openapitools.client.model.Data25AirPollutionGet200ResponseListInnerMain;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25AirPollutionGet200ResponseListInner
 */
@JsonPropertyOrder({
  Data25AirPollutionGet200ResponseListInner.JSON_PROPERTY_MAIN,
  Data25AirPollutionGet200ResponseListInner.JSON_PROPERTY_COMPONENTS
})
@JsonTypeName("_data_2_5_air_pollution_get_200_response_list_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25AirPollutionGet200ResponseListInner {
  public static final String JSON_PROPERTY_MAIN = "main";
  @javax.annotation.Nullable
  private Data25AirPollutionGet200ResponseListInnerMain main;

  public static final String JSON_PROPERTY_COMPONENTS = "components";
  @javax.annotation.Nullable
  private Data25AirPollutionGet200ResponseListInnerComponents components;

  public Data25AirPollutionGet200ResponseListInner() {
  }

  public Data25AirPollutionGet200ResponseListInner main(@javax.annotation.Nullable Data25AirPollutionGet200ResponseListInnerMain main) {
    
    this.main = main;
    return this;
  }

  /**
   * Get main
   * @return main
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Data25AirPollutionGet200ResponseListInnerMain getMain() {
    return main;
  }


  @JsonProperty(value = JSON_PROPERTY_MAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMain(@javax.annotation.Nullable Data25AirPollutionGet200ResponseListInnerMain main) {
    this.main = main;
  }

  public Data25AirPollutionGet200ResponseListInner components(@javax.annotation.Nullable Data25AirPollutionGet200ResponseListInnerComponents components) {
    
    this.components = components;
    return this;
  }

  /**
   * Get components
   * @return components
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COMPONENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Data25AirPollutionGet200ResponseListInnerComponents getComponents() {
    return components;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPONENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComponents(@javax.annotation.Nullable Data25AirPollutionGet200ResponseListInnerComponents components) {
    this.components = components;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25AirPollutionGet200ResponseListInner data25AirPollutionGet200ResponseListInner = (Data25AirPollutionGet200ResponseListInner) o;
    return Objects.equals(this.main, data25AirPollutionGet200ResponseListInner.main) &&
        Objects.equals(this.components, data25AirPollutionGet200ResponseListInner.components);
  }

  @Override
  public int hashCode() {
    return Objects.hash(main, components);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25AirPollutionGet200ResponseListInner {\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

