/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Data25ForecastGet200ResponseListInnerMain;
import org.openapitools.client.model.Data25ForecastGet200ResponseListInnerWeatherInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25ForecastGet200ResponseListInner
 */
@JsonPropertyOrder({
  Data25ForecastGet200ResponseListInner.JSON_PROPERTY_DT_TXT,
  Data25ForecastGet200ResponseListInner.JSON_PROPERTY_MAIN,
  Data25ForecastGet200ResponseListInner.JSON_PROPERTY_WEATHER
})
@JsonTypeName("_data_2_5_forecast_get_200_response_list_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25ForecastGet200ResponseListInner {
  public static final String JSON_PROPERTY_DT_TXT = "dt_txt";
  @javax.annotation.Nullable
  private String dtTxt;

  public static final String JSON_PROPERTY_MAIN = "main";
  @javax.annotation.Nullable
  private Data25ForecastGet200ResponseListInnerMain main;

  public static final String JSON_PROPERTY_WEATHER = "weather";
  @javax.annotation.Nullable
  private List<Data25ForecastGet200ResponseListInnerWeatherInner> weather = new ArrayList<>();

  public Data25ForecastGet200ResponseListInner() {
  }

  public Data25ForecastGet200ResponseListInner dtTxt(@javax.annotation.Nullable String dtTxt) {
    
    this.dtTxt = dtTxt;
    return this;
  }

  /**
   * Get dtTxt
   * @return dtTxt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DT_TXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDtTxt() {
    return dtTxt;
  }


  @JsonProperty(value = JSON_PROPERTY_DT_TXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDtTxt(@javax.annotation.Nullable String dtTxt) {
    this.dtTxt = dtTxt;
  }

  public Data25ForecastGet200ResponseListInner main(@javax.annotation.Nullable Data25ForecastGet200ResponseListInnerMain main) {
    
    this.main = main;
    return this;
  }

  /**
   * Get main
   * @return main
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Data25ForecastGet200ResponseListInnerMain getMain() {
    return main;
  }


  @JsonProperty(value = JSON_PROPERTY_MAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMain(@javax.annotation.Nullable Data25ForecastGet200ResponseListInnerMain main) {
    this.main = main;
  }

  public Data25ForecastGet200ResponseListInner weather(@javax.annotation.Nullable List<Data25ForecastGet200ResponseListInnerWeatherInner> weather) {
    
    this.weather = weather;
    return this;
  }

  public Data25ForecastGet200ResponseListInner addWeatherItem(Data25ForecastGet200ResponseListInnerWeatherInner weatherItem) {
    if (this.weather == null) {
      this.weather = new ArrayList<>();
    }
    this.weather.add(weatherItem);
    return this;
  }

  /**
   * Get weather
   * @return weather
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEATHER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Data25ForecastGet200ResponseListInnerWeatherInner> getWeather() {
    return weather;
  }


  @JsonProperty(value = JSON_PROPERTY_WEATHER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeather(@javax.annotation.Nullable List<Data25ForecastGet200ResponseListInnerWeatherInner> weather) {
    this.weather = weather;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25ForecastGet200ResponseListInner data25ForecastGet200ResponseListInner = (Data25ForecastGet200ResponseListInner) o;
    return Objects.equals(this.dtTxt, data25ForecastGet200ResponseListInner.dtTxt) &&
        Objects.equals(this.main, data25ForecastGet200ResponseListInner.main) &&
        Objects.equals(this.weather, data25ForecastGet200ResponseListInner.weather);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dtTxt, main, weather);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25ForecastGet200ResponseListInner {\n");
    sb.append("    dtTxt: ").append(toIndentedString(dtTxt)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    weather: ").append(toIndentedString(weather)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

