/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Data25AirPollutionGet200ResponseListInnerMain
 */
@JsonPropertyOrder({
  Data25AirPollutionGet200ResponseListInnerMain.JSON_PROPERTY_AQI
})
@JsonTypeName("_data_2_5_air_pollution_get_200_response_list_inner_main")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25AirPollutionGet200ResponseListInnerMain {
  public static final String JSON_PROPERTY_AQI = "aqi";
  @javax.annotation.Nullable
  private Integer aqi;

  public Data25AirPollutionGet200ResponseListInnerMain() {
  }

  public Data25AirPollutionGet200ResponseListInnerMain aqi(@javax.annotation.Nullable Integer aqi) {
    
    this.aqi = aqi;
    return this;
  }

  /**
   * Get aqi
   * @return aqi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AQI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAqi() {
    return aqi;
  }


  @JsonProperty(value = JSON_PROPERTY_AQI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAqi(@javax.annotation.Nullable Integer aqi) {
    this.aqi = aqi;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25AirPollutionGet200ResponseListInnerMain data25AirPollutionGet200ResponseListInnerMain = (Data25AirPollutionGet200ResponseListInnerMain) o;
    return Objects.equals(this.aqi, data25AirPollutionGet200ResponseListInnerMain.aqi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aqi);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25AirPollutionGet200ResponseListInnerMain {\n");
    sb.append("    aqi: ").append(toIndentedString(aqi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

