/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Geo10DirectGet200ResponseInner
 */
@JsonPropertyOrder({
  Geo10DirectGet200ResponseInner.JSON_PROPERTY_NAME,
  Geo10DirectGet200ResponseInner.JSON_PROPERTY_LOCAL_NAMES,
  Geo10DirectGet200ResponseInner.JSON_PROPERTY_LAT,
  Geo10DirectGet200ResponseInner.JSON_PROPERTY_LON,
  Geo10DirectGet200ResponseInner.JSON_PROPERTY_COUNTRY,
  Geo10DirectGet200ResponseInner.JSON_PROPERTY_STATE
})
@JsonTypeName("_geo_1_0_direct_get_200_response_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T16:22:21.557714607Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Geo10DirectGet200ResponseInner {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_LOCAL_NAMES = "local_names";
  @javax.annotation.Nullable
  private Map<String, String> localNames = new HashMap<>();

  public static final String JSON_PROPERTY_LAT = "lat";
  @javax.annotation.Nullable
  private BigDecimal lat;

  public static final String JSON_PROPERTY_LON = "lon";
  @javax.annotation.Nullable
  private BigDecimal lon;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private String state;

  public Geo10DirectGet200ResponseInner() {
  }

  public Geo10DirectGet200ResponseInner name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public Geo10DirectGet200ResponseInner localNames(@javax.annotation.Nullable Map<String, String> localNames) {
    
    this.localNames = localNames;
    return this;
  }

  public Geo10DirectGet200ResponseInner putLocalNamesItem(String key, String localNamesItem) {
    if (this.localNames == null) {
      this.localNames = new HashMap<>();
    }
    this.localNames.put(key, localNamesItem);
    return this;
  }

  /**
   * Get localNames
   * @return localNames
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCAL_NAMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getLocalNames() {
    return localNames;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCAL_NAMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalNames(@javax.annotation.Nullable Map<String, String> localNames) {
    this.localNames = localNames;
  }

  public Geo10DirectGet200ResponseInner lat(@javax.annotation.Nullable BigDecimal lat) {
    
    this.lat = lat;
    return this;
  }

  /**
   * Get lat
   * @return lat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLat() {
    return lat;
  }


  @JsonProperty(value = JSON_PROPERTY_LAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLat(@javax.annotation.Nullable BigDecimal lat) {
    this.lat = lat;
  }

  public Geo10DirectGet200ResponseInner lon(@javax.annotation.Nullable BigDecimal lon) {
    
    this.lon = lon;
    return this;
  }

  /**
   * Get lon
   * @return lon
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getLon() {
    return lon;
  }


  @JsonProperty(value = JSON_PROPERTY_LON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLon(@javax.annotation.Nullable BigDecimal lon) {
    this.lon = lon;
  }

  public Geo10DirectGet200ResponseInner country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Get country
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNTRY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public Geo10DirectGet200ResponseInner state(@javax.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Geo10DirectGet200ResponseInner geo10DirectGet200ResponseInner = (Geo10DirectGet200ResponseInner) o;
    return Objects.equals(this.name, geo10DirectGet200ResponseInner.name) &&
        Objects.equals(this.localNames, geo10DirectGet200ResponseInner.localNames) &&
        Objects.equals(this.lat, geo10DirectGet200ResponseInner.lat) &&
        Objects.equals(this.lon, geo10DirectGet200ResponseInner.lon) &&
        Objects.equals(this.country, geo10DirectGet200ResponseInner.country) &&
        Objects.equals(this.state, geo10DirectGet200ResponseInner.state);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, localNames, lat, lon, country, state);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Geo10DirectGet200ResponseInner {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    localNames: ").append(toIndentedString(localNames)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

