/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openweather.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import openweather.model.Data25WeatherGet200ResponseMain;
import openweather.model.Data25WeatherGet200ResponseWeatherInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import openweather.JSON;

/**
 * Data25WeatherGet200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T07:32:12.530684852Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25WeatherGet200Response {
  public static final String SERIALIZED_NAME_WEATHER = "weather";
  @SerializedName(SERIALIZED_NAME_WEATHER)
  @javax.annotation.Nullable
  private List<Data25WeatherGet200ResponseWeatherInner> weather = new ArrayList<>();

  public static final String SERIALIZED_NAME_MAIN = "main";
  @SerializedName(SERIALIZED_NAME_MAIN)
  @javax.annotation.Nullable
  private Data25WeatherGet200ResponseMain main;

  public Data25WeatherGet200Response() {
  }

  public Data25WeatherGet200Response weather(@javax.annotation.Nullable List<Data25WeatherGet200ResponseWeatherInner> weather) {
    this.weather = weather;
    return this;
  }

  public Data25WeatherGet200Response addWeatherItem(Data25WeatherGet200ResponseWeatherInner weatherItem) {
    if (this.weather == null) {
      this.weather = new ArrayList<>();
    }
    this.weather.add(weatherItem);
    return this;
  }

  /**
   * Get weather
   * @return weather
   */
  @javax.annotation.Nullable
  public List<Data25WeatherGet200ResponseWeatherInner> getWeather() {
    return weather;
  }

  public void setWeather(@javax.annotation.Nullable List<Data25WeatherGet200ResponseWeatherInner> weather) {
    this.weather = weather;
  }


  public Data25WeatherGet200Response main(@javax.annotation.Nullable Data25WeatherGet200ResponseMain main) {
    this.main = main;
    return this;
  }

  /**
   * Get main
   * @return main
   */
  @javax.annotation.Nullable
  public Data25WeatherGet200ResponseMain getMain() {
    return main;
  }

  public void setMain(@javax.annotation.Nullable Data25WeatherGet200ResponseMain main) {
    this.main = main;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25WeatherGet200Response data25WeatherGet200Response = (Data25WeatherGet200Response) o;
    return Objects.equals(this.weather, data25WeatherGet200Response.weather) &&
        Objects.equals(this.main, data25WeatherGet200Response.main);
  }

  @Override
  public int hashCode() {
    return Objects.hash(weather, main);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25WeatherGet200Response {\n");
    sb.append("    weather: ").append(toIndentedString(weather)).append("\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("coord", "weather", "base", "main", "visibility", "wind", "clouds", "dt", "sys", "timezone", "id", "name", "cod"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Data25WeatherGet200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Data25WeatherGet200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Data25WeatherGet200Response is not found in the empty JSON string", Data25WeatherGet200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Data25WeatherGet200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Data25WeatherGet200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("weather") != null && !jsonObj.get("weather").isJsonNull()) {
        JsonArray jsonArrayweather = jsonObj.getAsJsonArray("weather");
        if (jsonArrayweather != null) {
          // ensure the json data is an array
          if (!jsonObj.get("weather").isJsonArray()) {
            throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `weather` to be an array in the JSON string but got `%s`", jsonObj.get("weather").toString()));
          }

          // validate the optional field `weather` (array)
          for (int i = 0; i < jsonArrayweather.size(); i++) {
            Data25WeatherGet200ResponseWeatherInner.validateJsonElement(jsonArrayweather.get(i));
          };
        }
      }
      // validate the optional field `main`
      if (jsonObj.get("main") != null && !jsonObj.get("main").isJsonNull()) {
        Data25WeatherGet200ResponseMain.validateJsonElement(jsonObj.get("main"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Data25WeatherGet200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Data25WeatherGet200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Data25WeatherGet200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Data25WeatherGet200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<Data25WeatherGet200Response>() {
           @Override
           public void write(JsonWriter out, Data25WeatherGet200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Data25WeatherGet200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Data25WeatherGet200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Data25WeatherGet200Response
   * @throws IOException if the JSON string is invalid with respect to Data25WeatherGet200Response
   */
  public static Data25WeatherGet200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Data25WeatherGet200Response.class);
  }

  /**
   * Convert an instance of Data25WeatherGet200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

