/*
 * OpenWeather Proxy API
 * API for fetching weather, air quality, and geocoding data from OpenWeatherMap.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package openweather.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import openweather.model.Data25AirPollutionGet200ResponseListInnerComponents;
import openweather.model.Data25AirPollutionGet200ResponseListInnerMain;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import openweather.JSON;

/**
 * Data25AirPollutionGet200ResponseListInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-15T07:32:12.530684852Z[Etc/UTC]", comments = "Generator version: 7.17.0-SNAPSHOT")
public class Data25AirPollutionGet200ResponseListInner {
  public static final String SERIALIZED_NAME_MAIN = "main";
  @SerializedName(SERIALIZED_NAME_MAIN)
  @javax.annotation.Nullable
  private Data25AirPollutionGet200ResponseListInnerMain main;

  public static final String SERIALIZED_NAME_COMPONENTS = "components";
  @SerializedName(SERIALIZED_NAME_COMPONENTS)
  @javax.annotation.Nullable
  private Data25AirPollutionGet200ResponseListInnerComponents components;

  public Data25AirPollutionGet200ResponseListInner() {
  }

  public Data25AirPollutionGet200ResponseListInner main(@javax.annotation.Nullable Data25AirPollutionGet200ResponseListInnerMain main) {
    this.main = main;
    return this;
  }

  /**
   * Get main
   * @return main
   */
  @javax.annotation.Nullable
  public Data25AirPollutionGet200ResponseListInnerMain getMain() {
    return main;
  }

  public void setMain(@javax.annotation.Nullable Data25AirPollutionGet200ResponseListInnerMain main) {
    this.main = main;
  }


  public Data25AirPollutionGet200ResponseListInner components(@javax.annotation.Nullable Data25AirPollutionGet200ResponseListInnerComponents components) {
    this.components = components;
    return this;
  }

  /**
   * Get components
   * @return components
   */
  @javax.annotation.Nullable
  public Data25AirPollutionGet200ResponseListInnerComponents getComponents() {
    return components;
  }

  public void setComponents(@javax.annotation.Nullable Data25AirPollutionGet200ResponseListInnerComponents components) {
    this.components = components;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Data25AirPollutionGet200ResponseListInner data25AirPollutionGet200ResponseListInner = (Data25AirPollutionGet200ResponseListInner) o;
    return Objects.equals(this.main, data25AirPollutionGet200ResponseListInner.main) &&
        Objects.equals(this.components, data25AirPollutionGet200ResponseListInner.components);
  }

  @Override
  public int hashCode() {
    return Objects.hash(main, components);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Data25AirPollutionGet200ResponseListInner {\n");
    sb.append("    main: ").append(toIndentedString(main)).append("\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("main", "components", "dt"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Data25AirPollutionGet200ResponseListInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Data25AirPollutionGet200ResponseListInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in Data25AirPollutionGet200ResponseListInner is not found in the empty JSON string", Data25AirPollutionGet200ResponseListInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Data25AirPollutionGet200ResponseListInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Data25AirPollutionGet200ResponseListInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `main`
      if (jsonObj.get("main") != null && !jsonObj.get("main").isJsonNull()) {
        Data25AirPollutionGet200ResponseListInnerMain.validateJsonElement(jsonObj.get("main"));
      }
      // validate the optional field `components`
      if (jsonObj.get("components") != null && !jsonObj.get("components").isJsonNull()) {
        Data25AirPollutionGet200ResponseListInnerComponents.validateJsonElement(jsonObj.get("components"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Data25AirPollutionGet200ResponseListInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Data25AirPollutionGet200ResponseListInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Data25AirPollutionGet200ResponseListInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Data25AirPollutionGet200ResponseListInner.class));

       return (TypeAdapter<T>) new TypeAdapter<Data25AirPollutionGet200ResponseListInner>() {
           @Override
           public void write(JsonWriter out, Data25AirPollutionGet200ResponseListInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Data25AirPollutionGet200ResponseListInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Data25AirPollutionGet200ResponseListInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Data25AirPollutionGet200ResponseListInner
   * @throws IOException if the JSON string is invalid with respect to Data25AirPollutionGet200ResponseListInner
   */
  public static Data25AirPollutionGet200ResponseListInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Data25AirPollutionGet200ResponseListInner.class);
  }

  /**
   * Convert an instance of Data25AirPollutionGet200ResponseListInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

